# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.4.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "a2da443687aaa18bbccf4ce1668868d6782da6f045d0faca0960883366fc1550"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "a6cd8a7a3e6b9f25e591283c375b885cf0f3618f148b7d525597253f4f38abcb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "5656ab3d24d19f8af13e04b46c60188850caf5ff8cdb9a3e77d9ad27a2168650"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "92411d40a0630d762d27a0d2b10b5998a9dd34eda720b795ccee7973b6710b12"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
