# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound-cli" do
  name "hubbound-cli"
  desc "Hubbound CLI (user-owned, no background service)."
  homepage "https://hubbound.net"
  version "0.4.59"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"

  on_macos do
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound-cli_darwin_arm64.tar.gz"
      sha256 "2844eef18b934d97492d42360513c9071d056b331eea29fd7cfcb3631f6b19ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound-cli_linux_amd64.tar.gz"
      sha256 "c53a8c96d72e8effa13fa734f593f37d2987e3b04ddc100254d12f69d3cb9923"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound-cli_linux_arm64.tar.gz"
      sha256 "51f02287df6f06865052a040e9f1d771c97268057d6561dfdeeb89dcf2e8f74f"
    end
  end

  # No zap stanza required
end
