# This file is generated by packaging/homebrew/generate-runtime-cask.py.
# Do not replace the PKG artifact with a Caskroom binary: hubboundd must run
# from the protected system root and must be registered by the native installer.
cask "hubbound-runtime" do
  depends_on arch: :arm64

  version "0.4.36"
  sha256 "4ed02f61d85233cee84e66a409b5999e8f619a0e3ef447226fba3edc712460af"

  on_macos do
    url "https://github.com/hubbound/hubbound/releases/download/v0.4.36/HubBound-Runtime-v#{version}-arm64.pkg"
  end

  name "HubBound Runtime"
  desc "HubBound protected daemon, user agent, and privileged helper"
  homepage "https://hubbound.net"

  pkg "HubBound-Runtime-v#{version}-arm64.pkg"

  uninstall launchctl: "net.hubbound.agent",
            script: {
              executable: "/Library/Application Support/hubbound/current/hubbound-helper",
              args: ["system", "uninstall", "--system-root", "/Library/Application Support/hubbound"],
              must_succeed: true,
              sudo: true,
            },
            pkgutil: "net.hubbound.runtime",
            delete: [
              "/Library/LaunchDaemons/hubboundd.plist",
              "/Library/Application Support/hubbound",
              "/Library/LaunchAgents/net.hubbound.agent.plist",
            ]

  caveats <<~EOS
    HubBound Runtime installs a protected system daemon and a global LaunchAgent
    that runs as each logged-in user.
    Homebrew may request administrator credentials during install or uninstall.
  EOS
end
