# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.4.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "e7c1afa7a7e96063bcaec678cf7752e467681120742f6fdaaef325dbb1db1b1f"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "d6214a3ea713e1f9b182064f470b851b32167789318cbe3b096de0d40901cd6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "0fbb166465535692fde3c41a3ffaad090a142043ab774d024d5e0c7fb433d660"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "8cabb0ceb4093ef48a96cc766907b8d3a24d9de8a2774dd64a03d843f95a6381"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
