# This file is generated by packaging/homebrew/generate-runtime-cask.py.
# Do not replace the PKG artifact with a Caskroom binary: hubboundd must run
# from the protected system root and must be registered by the native installer.
cask "hubbound-runtime" do
  arch arm: "arm64", intel: "amd64"

  version "0.4.30"
  sha256 arm:   "0d6cf4db2014e6b44945b8d7cecd65a6b10b807337498aafe9a2d396e80a3631",
         intel: "0e5e648ce09a0a3f6c40fe4e1e828b1ef8c0e783e36f01afeb35432a7cd971c2"

  on_macos do
    url "https://github.com/hubbound/hubbound/releases/download/v0.4.30/HubBound-Runtime-v#{version}-#{arch}.pkg"
  end

  name "HubBound Runtime"
  desc "HubBound protected daemon, user agent, and privileged helper"
  homepage "https://hubbound.net"

  pkg "HubBound-Runtime-v#{version}-#{arch}.pkg"

  uninstall launchctl: "net.hubbound.agent",
            script: {
              executable: "/Library/Application Support/hubbound/current/hubbound-helper",
              args: ["system", "uninstall", "--system-root", "/Library/Application Support/hubbound"],
              must_succeed: true,
              sudo: true,
            },
            pkgutil: "net.hubbound.runtime",
            delete: [
              "/Library/LaunchDaemons/hubboundd.plist",
              "/Library/Application Support/hubbound",
              "/Library/LaunchAgents/net.hubbound.agent.plist",
            ]

  caveats <<~EOS
    HubBound Runtime installs a protected system daemon and a global LaunchAgent
    that runs as each logged-in user.
    Homebrew may request administrator credentials during install or uninstall.
  EOS
end
