# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubbound" do
  name "hubbound"
  desc "Hubbound CLI, daemon, user agent, and privileged helper."
  homepage "https://hubbound.net"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubbound"
  binary "hubboundd"
  binary "hubbound-agent"
  binary "hubbound-helper"

  on_macos do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_amd64.tar.gz"
      sha256 "ff6dfb27ea8b78e601d33faa0c80256d69d1ffe4d3fdf530884ad7b34d322f83"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_darwin_arm64.tar.gz"
      sha256 "a2ba4fbe3596a4b0348cbedb07ef8fb3dcc20c660916d0490a154dc676f578dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_amd64.tar.gz"
      sha256 "1532aee4fd33ae5a5e4312432369ce30a527c66522296dd392dad125fbb40410"
    end
    on_arm do
      url "https://github.com/hubbound/hubbound/releases/download/v#{version}/hubbound_linux_arm64.tar.gz"
      sha256 "15c0889d0f1e7bc0fe0dda47678240d4e01dbff0fa0d58044e365e79a6dcfb37"
    end
  end

  service "run [opt_bin/"hubbound-agent", "run"]
keep_alive true
log_path var/"log/hubbound-agent.log"
error_log_path var/"log/hubbound-agent.err.log"
"

  # No zap stanza required
end
