# This file is generated by packaging/homebrew/generate-runtime-cask.py.
# Do not replace the PKG artifact with a Caskroom binary: hubboundd must run
# from the protected system root and must be registered by the native installer.
cask "hubbound-runtime" do
  arch arm: "arm64", intel: "amd64"

  version "0.4.26"
  sha256 arm:   "f789db4ea87332bd7d34533350f848769b879eb9e718092c8b303987de4d7adb",
         intel: "b27b5f45051c0a1100a2e602f2f099458fa3e5d5b7c685ad4db74b3ee7419cf2"

  on_macos do
    url "https://github.com/hubbound/hubbound/releases/download/v0.4.26/HubBound-Runtime-v#{version}-#{arch}.pkg"
  end

  name "HubBound Runtime"
  desc "HubBound protected daemon, user agent, and privileged helper"
  homepage "https://hubbound.net"

  pkg "HubBound-Runtime-v#{version}-#{arch}.pkg"

  uninstall launchctl: "net.hubbound.agent",
            script: {
              executable: "/Library/Application Support/hubbound/current/hubbound-helper",
              args: ["system", "uninstall", "--system-root", "/Library/Application Support/hubbound"],
              must_succeed: true,
              sudo: true,
            },
            pkgutil: "net.hubbound.runtime",
            delete: [
              "/Library/LaunchDaemons/hubboundd.plist",
              "/Library/Application Support/hubbound",
              "/Library/LaunchAgents/net.hubbound.agent.plist",
            ]

  caveats <<~EOS
    HubBound Runtime installs a protected system daemon and a global LaunchAgent
    that runs as each logged-in user.
    Homebrew may request administrator credentials during install or uninstall.
  EOS
end
